{{- range $key, $val := .Values.ingress }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $key }}-upstream
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/server-snippet: |
      access_log /var/log/nginx/{{ $key }}.access.log;
      error_log /var/log/nginx/{{ $key }}.error.log;
      gzip on;
      gzip_disable "msie6";
      gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/javascript;
    {{- with $val.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  tls:
  - hosts:
    - {{ $val.domainName }}
    secretName: {{ $val.secretName }}
  rules:
  - host: {{ $val.domainName }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $.Values.applicationName }}-upstream
            port:
              number: 3000
{{- end }}
